### ISSUE TITLE
Deltabot error message

### ISSUE THREAD

**Issue by tbdabbholm** [hallidev/delta-bot-four#7]
I tried adding those comments that Ansuz sent you the error messages for with www.reddit instead of old.reddit and got this message:

Core.Foundation.AssertionException at DeltaBotFour.Infrastructure.Implementation.DeltaAwarder.Award(DB4Thing comment) in D:\Projects\delta-bot-four\DeltaBotFour.Infrastructure\Implementation\DeltaAwarder.cs:line 46 at DeltaBotFour.Infrastructure.Implementation.PrivateMessageHandlers.ModAddDeltaPMHandler.Handle(DB4Thing privateMessage) in D:\Projects\delta-bot-four\DeltaBotFour.Infrastructure\Implementation\PrivateMessageHandlers\ModAddDeltaPMHandler.cs:line 81

Just wanted to know what the issue was there.

**Comment by hallidev** [comment]
This is an internal error DeltaBot generates when it has already awarded a delta for a comment and it gets a request to add a delta to the same comment, and that comment isn't an edit. It's basically a safety check. It's hard for me to know exactly what went on in this case. It's likely it happened right after a DeltaBot restart.

Please advise if you see this message again. I'll close for now as a number of changes have been made since this happened.
